### PR TITLE
Made template generator generate build.gradle with including src/main/generated

### PR DESCRIPTION
**Pull request by O7410**
issue about this: https://github.com/FabricMC/fabricmc.net/issues/69

### CODE REVIEW

**Comment by modmuss50** [comment]
This should be handled by loom here: <https://github.com/FabricMC/fabric-loom/blob/dev/1.4/src/main/java/net/fabricmc/loom/configuration/FabricApiExtension.java#L118-L121> when using `configureDataGeneration()`

**Comment by O7410** [comment]
well it itsn't

**Comment by modmuss50** [comment]
This needs fixing in loom if thats the case, let me see if I can reproduce this issue.

**Comment by O7410** [comment]
steps to reproduce:

1. download the template with these options image
2. put something manually in src/main/generated (or generate with datagen)
3. run the client
4. it's not working
5. close the game
6. add the code to build.gradle
7. reload gradle
8. run the client again
9. it's working

**Comment by modmuss50** [comment]
Thanks, I have fixed this in loom. 👍

**Pull request closed without merging**
