### PR TITLE
Update 2022-11-24-1193.md

### PR DESCRIPTION
**Pull request by Ayutac**
small fix

### CODE REVIEW

**Comment by Ayutac** [comment]
huh, no idea where the second change comes from or what it is? :thinking:

**Review by modmuss50 — CHANGES_REQUESTED** [review]
I dont think this is wrong.

**Comment by Technici4n** [comment]
Looks correct compared to 1.19.2.

**Comment by Technici4n** [comment]
For example look at: https://github.com/TechReborn/TechReborn/blob/4d5f8d097f98cc8051e3cc57cf348e6749f8646a/RebornCore/src/main/java/reborncore/RebornRegistry.java#L57

**Comment by Ayutac** [comment]
I asked in mod-dev-talk and apple agreed. My mistake then.

**Pull request closed without merging**
